### ISSUE TITLE
Langstream does not work on windows.

### ISSUE THREAD

**Issue by suleymanekmekci** [LangStream/langstream#737]
` langstream -v docker run test -app yamls -s secret/secrets.yaml
Tenant: default
Application: test
Application directory: C:\lstream\yamls
Running all the agents in the application
Instance file: null
Secrets file: C:\lstream\secret\secrets.yaml
Start broker: true
Start S3: true
Start Database: true
Start Webservices true
Using docker image: ghcr.io/langstream/langstream-runtime-tester:0.5.0
Using config file C:\Users\macha\.langstream\config
Using default instance file that connects to the Kafka broker inside the docker container
profile local-docker-run updated
Using config file C:\Users\macha\.langstream\config
Internal error: java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException
        at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2166)
        at ai.langstream.cli.commands.docker.LocalRunApplicationCmd.makeDirOrFileReadable(LocalRunApplicationCmd.java:514)
        at ai.langstream.cli.commands.docker.LocalRunApplicationCmd.makeDirOrFileReadable(LocalRunApplicationCmd.java:509)
        at ai.langstream.cli.commands.docker.LocalRunApplicationCmd.prepareAppDirectory(LocalRunApplicationCmd.java:494)
        at ai.langstream.cli.commands.docker.LocalRunApplicationCmd.executeOnDocker(LocalRunApplicationCmd.java:319)
        at ai.langstream.cli.commands.docker.LocalRunApplicationCmd.run(LocalRunApplicationCmd.java:263)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at ai.langstream.cli.LangStreamCLI.execute(LangStreamCLI.java:74)
        at ai.langstream.cli.LangStreamCLI.main(LangStreamCLI.java:52)
Cleaning environment
Deleting temporary file: C:\Users\macha\.langstream\tmp\.langstream_app_590692518254300`

java version 17
langstream 0.5.0

**Comment by msmygit** [comment]
Dup to #716 and related to #526
